CREATE TABLE IF NOT EXISTS public.participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(120) NOT NULL,
  telephone VARCHAR(30) NOT NULL,
  email VARCHAR(160),
  ticket_code VARCHAR(80) NOT NULL UNIQUE,
  qr_code TEXT NOT NULL,
  statut VARCHAR(20) NOT NULL DEFAULT 'active',
  date_achat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  date_scan TIMESTAMPTZ,
  CONSTRAINT participants_statut_check CHECK (statut IN ('active', 'used'))
);

CREATE INDEX IF NOT EXISTS idx_participants_ticket_code
  ON public.participants (ticket_code);

CREATE INDEX IF NOT EXISTS idx_participants_statut
  ON public.participants (statut);

ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;

-- L'application Express se connecte avec une chaine Postgres cote serveur.
-- Aucune policy publique n'est creee afin d'eviter l'acces direct depuis le navigateur.


CREATE TABLE IF NOT EXISTS public.users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nom VARCHAR(120) NOT NULL,
  telephone VARCHAR(30),
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'participant',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
