-- ============================================================
-- TABLE: participants
-- Chaque ligne = 1 ticket physique (1 personne peut en avoir N)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.participants (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom           VARCHAR(120) NOT NULL,
  prenom        VARCHAR(120) NOT NULL DEFAULT '',
  telephone     VARCHAR(30)  NOT NULL,
  vendeur       VARCHAR(120) NOT NULL DEFAULT '',
  date_achat    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  ticket_code   VARCHAR(80)  NOT NULL UNIQUE,
  qr_code       TEXT         NOT NULL,
  statut        VARCHAR(20)  NOT NULL DEFAULT 'active',
  date_scan     TIMESTAMPTZ,
  CONSTRAINT participants_statut_check CHECK (statut IN ('active', 'used', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_participants_ticket_code ON public.participants (ticket_code);
CREATE INDEX IF NOT EXISTS idx_participants_statut       ON public.participants (statut);

ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- TABLE: users  (admins + controleurs uniquement)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.users (
  id            UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  nom           VARCHAR(120) NOT NULL,
  email         VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role          VARCHAR(50)  NOT NULL DEFAULT 'controleur'
                CONSTRAINT users_role_check CHECK (role IN ('admin', 'controleur')),
  actif         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- TABLE: audit_logs  (journal des actions)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utilisateur VARCHAR(160) NOT NULL,
  role        VARCHAR(50)  NOT NULL,
  action      VARCHAR(100) NOT NULL,
  details     TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
