-- ============================================================
-- MIGRATION MINIMALE — À exécuter dans le SQL Editor de Supabase
-- Ajoute les colonnes manquantes sans supprimer les données existantes
-- ============================================================

-- 1. Ajouter prenom et vendeur à la table participants (si pas déjà présents)
ALTER TABLE public.participants
  ADD COLUMN IF NOT EXISTS prenom  VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS vendeur VARCHAR(120) NOT NULL DEFAULT '';

-- 2. Créer la table audit_logs si elle n'existe pas
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utilisateur VARCHAR(160) NOT NULL,
  role        VARCHAR(50)  NOT NULL,
  action      VARCHAR(100) NOT NULL,
  details     TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 3. S'assurer que la table users a le bon role constraint
-- (Si vous avez des utilisateurs avec role='participant', vous devrez les supprimer d'abord)
ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE public.users
  ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'controleur'));
